/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package blocker;

import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author l
 */
public class GUI_PROT extends javax.swing.JFrame {

    /**
     * Creates new form GUI_PROT
     */
    
    private Blocker block;
    private ArrayList<String> programs;
    private ArrayList<String> webPages;
    private String password;
    private int passLength=15;
    private int timeOfBlockade=5;
    private TimeActual timeActual;
    private  Timer timer1;
    
    public GUI_PROT() throws FileNotFoundException, UnsupportedEncodingException {
        initComponents();
        this.password= Password_Generator.generatePassword(passLength);
        this.jLPassword.setText(password);
        this.block = new Blocker();
        this.programs = new ArrayList<String>();
        this.webPages = new ArrayList<String>();
        this.jPanelMain.setVisible(true);
        this.jPanelProperties.setVisible(false);
        this.jPChosingPrograms.setVisible(false);
        this.timeActual = new TimeActual(this.jLTimeToEndActual ,this.timeOfBlockade);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Programy","exe");
        this.jFileChooserPrograms.setFileFilter(filter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMain = new javax.swing.JPanel();
        jLTimeToEnd = new javax.swing.JLabel();
        jLTimeToEndActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBStartBlock = new javax.swing.JButton();
        jBProperties = new javax.swing.JButton();
        jBStopBlock = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLPassword = new javax.swing.JLabel();
        jL01 = new javax.swing.JLabel();
        jLBlockedPrograms = new javax.swing.JLabel();
        jLBlockedWebPages = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelProperties = new javax.swing.JPanel();
        jBAddPrograms = new javax.swing.JButton();
        jBAddWebPages = new javax.swing.JButton();
        jBChangeTime = new javax.swing.JButton();
        jBChangePasswordLength = new javax.swing.JButton();
        jTFWebPage = new javax.swing.JTextField();
        jTFTime = new javax.swing.JTextField();
        jTFPasswordLength = new javax.swing.JTextField();
        jBackToMain = new javax.swing.JButton();
        jPChosingPrograms = new javax.swing.JPanel();
        jFileChooserPrograms = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelMain.setLayout(new java.awt.GridBagLayout());

        jLTimeToEnd.setText("Czas do końca blokady");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanelMain.add(jLTimeToEnd, gridBagConstraints);

        jLTimeToEndActual.setText("Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanelMain.add(jLTimeToEndActual, gridBagConstraints);

        jLabel3.setText("Blokowane strony");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanelMain.add(jLabel3, gridBagConstraints);

        jBStartBlock.setText("Start blocking");
        jBStartBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStartBlockActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanelMain.add(jBStartBlock, gridBagConstraints);

        jBProperties.setText("Ustawienia");
        jBProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPropertiesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanelMain.add(jBProperties, gridBagConstraints);

        jBStopBlock.setText("Stop blocking");
        jBStopBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStopBlockActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        jPanelMain.add(jBStopBlock, gridBagConstraints);

        jTextField1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanelMain.add(jTextField1, gridBagConstraints);

        jLPassword.setText("Pass");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanelMain.add(jLPassword, gridBagConstraints);

        jL01.setText("Blokowane programy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanelMain.add(jL01, gridBagConstraints);

        jLBlockedPrograms.setText("Blocked programs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanelMain.add(jLBlockedPrograms, gridBagConstraints);

        jLBlockedWebPages.setText("Blocked Web Pages");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanelMain.add(jLBlockedWebPages, gridBagConstraints);

        jLabel8.setText("Hasło");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanelMain.add(jLabel8, gridBagConstraints);

        getContentPane().add(jPanelMain, new java.awt.GridBagConstraints());

        jPanelProperties.setLayout(new java.awt.GridBagLayout());

        jBAddPrograms.setText("Dodaj programy");
        jBAddPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddProgramsActionPerformed(evt);
            }
        });
        jPanelProperties.add(jBAddPrograms, new java.awt.GridBagConstraints());

        jBAddWebPages.setText("Dodaj strony");
        jBAddWebPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddWebPagesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelProperties.add(jBAddWebPages, gridBagConstraints);

        jBChangeTime.setText("Zmień czas blokady");
        jBChangeTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangeTimeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanelProperties.add(jBChangeTime, gridBagConstraints);

        jBChangePasswordLength.setText("Zmień długość hasła");
        jBChangePasswordLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChangePasswordLengthActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanelProperties.add(jBChangePasswordLength, gridBagConstraints);

        jTFWebPage.setText("Strona");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanelProperties.add(jTFWebPage, gridBagConstraints);

        jTFTime.setText("Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanelProperties.add(jTFTime, gridBagConstraints);

        jTFPasswordLength.setText("Długość hasła");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanelProperties.add(jTFPasswordLength, gridBagConstraints);

        jBackToMain.setText("Wróć do menu głownego");
        jBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackToMainActionPerformed(evt);
            }
        });
        jPanelProperties.add(jBackToMain, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelProperties, new java.awt.GridBagConstraints());

        jPChosingPrograms.setLayout(new java.awt.GridLayout());

        jFileChooserPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserProgramsActionPerformed(evt);
            }
        });
        jPChosingPrograms.add(jFileChooserPrograms);

        getContentPane().add(jPChosingPrograms, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddProgramsActionPerformed
     
     this.jPChosingPrograms.setVisible(true);
     this.jPanelProperties.setVisible(false);
     int returnVal = this.jFileChooserPrograms.showOpenDialog(jLabel3);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.programs.add(this.jFileChooserPrograms.getSelectedFile().getName());
            this.jPanelProperties.setVisible(true);
            this.jPChosingPrograms.setVisible(false);
        }
        else{
            this.jPanelProperties.setVisible(true);
            this.jPChosingPrograms.setVisible(false);
        }
    }//GEN-LAST:event_jBAddProgramsActionPerformed

    private void jBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackToMainActionPerformed
        this.jPanelMain.setVisible(true);
        this.jPanelProperties.setVisible(false);
    }//GEN-LAST:event_jBackToMainActionPerformed

    private void jBPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPropertiesActionPerformed
        this.jPanelMain.setVisible(false);
        this.jPanelProperties.setVisible(true);
    }//GEN-LAST:event_jBPropertiesActionPerformed

    private void jFileChooserProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserProgramsActionPerformed
     
    }//GEN-LAST:event_jFileChooserProgramsActionPerformed

    private void jBChangePasswordLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangePasswordLengthActionPerformed
       this.passLength = Integer.parseInt(this.jTFPasswordLength.getText()); 
       this.password= Password_Generator.generatePassword(passLength);
       this.jLPassword.setText(password);
       this.jTFPasswordLength.setText("");
    }//GEN-LAST:event_jBChangePasswordLengthActionPerformed

    private void jBAddWebPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddWebPagesActionPerformed
       this.webPages.add(this.jTFWebPage.getText());
       this.jTFWebPage.setText("");
    }//GEN-LAST:event_jBAddWebPagesActionPerformed

    private void jBChangeTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChangeTimeActionPerformed
       this.timeOfBlockade= Integer.parseInt(this.jTFTime.getText());
       this.jTFTime.setText("");
    }//GEN-LAST:event_jBChangeTimeActionPerformed

    private void jBStopBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStopBlockActionPerformed
        String tmp = this.jTextField1.getText();
        if(tmp.equals(this.password) || this.jLTimeToEndActual.getText().equals(Integer.toString(0)+" seconds")){
            this.jTextField1.setText("Podałeś prawidłowe hasło");
            this.jBStartBlock.setEnabled(true);
            this.timer1.stop();
            this.jBProperties.setEnabled(true);
            this.block.stop();
        }
        else{
            this.jTextField1.setText("Nieprawidłowe hasło");
        }
    }//GEN-LAST:event_jBStopBlockActionPerformed

    private void jBStartBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStartBlockActionPerformed
        this.jBStartBlock.setEnabled(false);
        this.jBProperties.setEnabled(false);
        String tmp1="";
        for(String tmp: this.programs) tmp1= tmp1+" " +tmp;
        this.jLBlockedPrograms.setText(tmp1);
        tmp1="";
        for(String tmp: this.webPages) tmp1= tmp1+" " +tmp;
        this.jLBlockedWebPages.setText(tmp1);
        ActionListener t = new TimeActual(this.jLTimeToEndActual, this.timeOfBlockade);
       this.timer1 = new Timer(1000,t);
        timer1.start();
        // tutaj zaczyna się faktyczne działanie programu
        this.block.clearPrograms();
        this.block.clearWebpages();
        this.block.addPrograms(this.programs);
        this.block.addWebpages(this.webPages);
        this.block.changeTimeOfBlockade(this.timeOfBlockade);
        try {
            this.block.start();
        } catch (InterruptedException ex) {
        
        } catch (FileNotFoundException ex) {
          
        } catch (ExecutionException ex) {
          
        } catch (TimeoutException ex) {
           
        } catch (IOException ex) {
            
        }
        
    }//GEN-LAST:event_jBStartBlockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_PROT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_PROT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_PROT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_PROT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new GUI_PROT().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GUI_PROT.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(GUI_PROT.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddPrograms;
    private javax.swing.JButton jBAddWebPages;
    private javax.swing.JButton jBChangePasswordLength;
    private javax.swing.JButton jBChangeTime;
    private javax.swing.JButton jBProperties;
    private javax.swing.JButton jBStartBlock;
    private javax.swing.JButton jBStopBlock;
    private javax.swing.JButton jBackToMain;
    private javax.swing.JFileChooser jFileChooserPrograms;
    private javax.swing.JLabel jL01;
    private javax.swing.JLabel jLBlockedPrograms;
    private javax.swing.JLabel jLBlockedWebPages;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLTimeToEnd;
    private javax.swing.JLabel jLTimeToEndActual;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPChosingPrograms;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelProperties;
    private javax.swing.JTextField jTFPasswordLength;
    private javax.swing.JTextField jTFTime;
    private javax.swing.JTextField jTFWebPage;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
